---
- hosts: localhost
  gather_facts: false
  become: true

  tasks:
    - name: Create Docker network
      community.docker.docker_network:
        name: terra_network
        state: present

    - name: Pull Docker images
      community.docker.docker_image:
        name: "{{ item }}"
        source: pull
      loop:
        - nginx:latest
        - zhy7ne/8.1-fpm-alpine-z:2.0
        - zhy7ne/pxc_node0:3.0
        - percona/percona-xtradb-cluster:5.7

    - name: Create PHP-FPM containers
      community.docker.docker_container:
        name: "php_fpm{{ item }}"
        image: zhy7ne/8.1-fpm-alpine-z:2.0
        volumes:
          - "/home/zhy7ne/Projects/Fligno/Ansible/docker/web-lb-pxc-php/server-pages/im-pit/:/var/www/html/"
          - "/home/zhy7ne/Projects/Fligno/Ansible/docker/web-lb-pxc-php/server-pages/im-pit/index{{ item }}.php:/var/www/html/index.php"
        ports:
          - "{{ 9001 + item }}:9000"
        networks:
          - name: terra_network
      loop: "{{ range(1, 3) | list }}"

    - name: Create server containers
      community.docker.docker_container:
        name: "server{{ item }}"
        image: "nginx:latest"
        volumes:
          - "/home/zhy7ne/Projects/Fligno/Ansible/docker/web-lb-pxc-php/custom-configs/server{{ item }}-php.conf:/etc/nginx/conf.d/default.conf"
        ports:
          - "808{{ item }}:80"
        networks:
          - name: terra_network
      loop: "{{ range(1, 3) | list }}"

    - name: Create Load Balancer container
      community.docker.docker_container:
        name: lb
        image: nginx:latest
        volumes:
          - "/home/zhy7ne/Projects/Fligno/Ansible/docker/web-lb-pxc-php/custom-configs/load-balancer.conf:/etc/nginx/conf.d/default.conf"
        ports:
          - "8080:80"
        networks:
          - name: terra_network

    - name: Create PXC Bootstrap Node container
      community.docker.docker_container:
        name: pxc_node0
        image: zhy7ne/pxc_node0:3.0
        env: |
          MYSQL_ALLOW_EMPTY_PASSWORD=yes
          MYSQL_ROOT_PASSWORD=password
          MYSQL_INITDB_SKIP_TZINFO=yes
          XTRABACKUP_PASSWORD=password
          PXC_ENCRYPT_CLUSTER_TRAFFIC=0
        ports:
          - "33060:3306"
        networks:
          - name: terra_network

    # Uncomment the following tasks after starting the bootstrap node
    # - name: Create PXC Joiner Nodes containers
    #   community.docker.docker_container:
    #     name: "pxc_node{{ item }}"
    #     image: percona/percona-xtradb-cluster:5.7
    #     env: |
    #       MYSQL_ALLOW_EMPTY_PASSWORD=yes
    #       MYSQL_ROOT_PASSWORD=password
    #       MYSQL_INITDB_SKIP_TZINFO=yes
    #       XTRABACKUP_PASSWORD=password
    #       CLUSTER_NAME=terracluster
    #       CLUSTER_JOIN=pxc_node0
    #       name=pxc_node{{ item }}
    #       net=terra_network
    #       PXC_ENCRYPT_CLUSTER_TRAFFIC=0
    #     ports:
    #       - "{{ 33061 + item }}:3306"
    #     networks:
    #       - name: terra_network
    #   loop: "{{ range(1, 3) | list }}"
